### ISSUE TITLE
Missing driving time at finer spatial scales

### ISSUE THREAD

**Issue by Makosak** [healthyregions/oeps#71]
When exploring on the Explorer's dev version, switched to "nearest pharmacy" while in tract mode, and the map flipped to a state-level metric.

- Missing tract-level, zip, and county metrics for this measure
- Should investigate how many spatial access metrics are missing currently at these finer resolution scales

Finally, "nearest pharmacy" spatial metric is not useful at the state level. We may have to:
- Remove state (and county-level?) nearest metrics potentially? Start with state.
- Convert to % of tracts that are within some distance, to make more meaningful?

![Screen Shot 2024-11-25 at 10 31 06 AM](https://github.com/user-attachments/assets/71d9354d-5983-4383-952d-bbc4a544362b)

**Comment by mradamcox** [comment]
Good catch, something is up with this because it should only be available at tract/zip, not county/state. Looking into it.

**Comment by mradamcox** [comment]
Luckily this was just a mislabeled variable... "Driving Time (min) to nearest Pharmacy" is correctly available only at tract and zip levels, but the averaged version of that variable, which only exists at state and county levels, had mistakenly been given the same label... You thought you had selected the overall driving time but had actually selected the averaged. The fix is now in the dev build.
